name: Scheduled Tasks

on:
  schedule:
    # Runs every day at 12:00 UTC (you can change this)
    - cron: "0 12 * * *"

  workflow_dispatch:  # Allows manual trigger from GitHub

jobs:
  run-scheduled-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run maintenance script
        run: node run.js

      - name: Log task completion
        run: echo "Scheduled maintenance completed successfully on $(date)"
